json.id @contact.id
json.first_name @contact.first_name
json.middle_name @contact.middle_name
json.last_name @contact.last_name
json.full_name @contact.full_name
json.email @contact.email
json.phone_number @contact.phone_number
json.bio @contact.bio
json.the_time_it_was_created @contact.friendly_updated_at
json.the_full_phone_number @contact.japan_phone_number
